[tool.commitizen]
tag_format = "v$version"
version = "0.0.0"
version_scheme = "semver2"
version_provider = "uv"
# Set to true to allow bumping to 0.y.z from 0.(y-1).z when commit types normally trigger major bump.
# Recommended for initial development phases before 1.0.0.
major_version_zero = true

commit_msg_file = ".git/COMMIT_EDITMSG"
retry_after_failure = true
update_changelog_on_bump = true
changelog_merge_prerelease = true
