# .github/workflows/typecheck-python.yml
# See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Type Check Python Code

on:
  pull_request:
    paths:
      - "src/**/*.py"
      - "tests/**/*.py"
      - "noxfile.py"
      - "pyproject.toml"
      - "pyrightconfig.json"
      - ".github/workflows/typecheck-python.yml"
      - "**/*.pyi" # Include explicit type stub files
  push:
    branches:
      - main
      - master
    paths:
      - "src/**/*.py"
      - "tests/**/*.py"
      - "noxfile.py"
      - "pyproject.toml"
      - "pyrightconfig.json"
      - ".github/workflows/typecheck-python.yml"
      - "**/*.pyi"

  workflow_dispatch:

jobs:
  typecheck-python:
    name: Run Python Type Checks on ${{ matrix.os }}/${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        os: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up uv
        uses: astral-sh/setup-uv@d0d8abe699bfb85fec6de9f7adb5ae17292296ff # v6

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Python type checking
        run: uvx nox -s typecheck-${{ matrix.python-version }}
